### ISSUE TITLE
`RefCell` inside `Arc`

### ISSUE THREAD

**Issue by jonathanpwang** [axiom-crypto/halo2-wasm#8]
https://github.com/axiom-crypto/halo2-wasm/blob/b02413ca50c1914a5b39f0768ebd3d98a15cb84c/src/lib.rs#L73

Usually one uses either `Rc<RefCell>` if it is not intended to be thread-safe, or `Arc<Mutex>` if it is supposed to be thread-safe (the Mutex locks until the given thread gets access to the object). 

What is the intended use case here?

**Comment by rpalakkal** [comment]
Not intended to be thread-safe -- changed to `Rc<RefCell>` in a733ab8. Thanks.
